- **simulation**: an imitation of a real-world process
- **trial**: one of the events that make up a simluation

In [1]:
import numpy as np

In [38]:
flips = np.random.choice(['Heads', 'Tails'], size=100_000_000)

(flips == 'Heads').mean()

0.49991119

In [39]:
# How many heads do we get after flipping 2 coins?
# n trials = 2
# n of simulations = 10,000

How to do simulation with python and numpy

1. figure out a way to represent out data
1. create a matrix of random data, rows == simulations, columns == trials
1. apply an aggregate row-wise to get the results of each simulation
1. apply a final aggregate to get our probility


> What's the probility I get 2 or more herads after flipping 3 coins?

In [51]:
# 1 . represent our data -- 0 is tails, 1 is heads
# 2. create a matrix (nrows, ncols)
flips = np.random.choice([0,1], size=(10_000, 3))
flips

array([[0, 0, 1],
       [0, 1, 1],
       [0, 1, 0],
       ...,
       [1, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [52]:
# 3. apply an aggregate row-wise to get the results of each simulation
simulation_results = flips.sum(axis=1)
simulation_results

array([1, 2, 1, ..., 1, 0, 3])

In [53]:
# 4. apply a final aggregation to get the probability
(simulation_results >= 2).mean()

0.5006

>Out of all of our simulations, 50% of our coin flips were heads

In [104]:
# the p-keyword argument skews the odds
np.random.seed(123) #for reproduceability
np.random.choice(['a','b', 'c'], size=25, p=[.8, .1, .1])



array(['a', 'a', 'a', 'a', 'a', 'a', 'c', 'a', 'a', 'a', 'a', 'a', 'a',
       'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'a', 'a', 'a'],
      dtype='<U1')

In [72]:
np.random.seed(42)
np.random.uniform(size=100)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
       0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
       0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041,
       0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
       0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249,
       0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
       0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446,
       0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998,
       0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033,
       0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
       0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694,
       0.77224477, 0.19871568, 0.00552212, 0.81546143, 0.70685

In [106]:
# .random pulls numbers from a normal distribution, 
#and the numbers used are the mean and standard deviation
np.random.normal(3, 1, size=100)


array([1.5896988 , 2.25234868, 2.01513239, 2.25143132, 3.24036728,
       1.14436253, 1.2205452 , 0.24977574, 2.76584245, 2.30401882,
       1.22586594, 5.36160126, 3.03499308, 2.65535831, 2.27496771,
       4.03960617, 2.75827196, 2.88709464, 1.33930422, 3.01353855,
       3.33737412, 2.07337702, 3.27574741, 3.37085233, 4.17430715,
       0.96770752, 3.58250829, 2.2788242 , 1.2975764 , 3.76764147,
       3.37067905, 5.07545935, 3.12775769, 4.79988945, 4.23836635,
       3.91375695, 3.46626803, 3.12503966, 2.80234908, 2.27196508,
       2.38968658, 2.12695103, 3.15646903, 3.28655207, 3.8677178 ,
       4.26751791, 5.10783998, 2.76391055, 2.76791817, 1.92186059,
       4.16318454, 3.52249007, 4.84436521, 3.69556401, 2.8183108 ,
       2.57773935, 4.01172044, 2.93324259, 2.84393611, 4.58346474,
       2.21340602, 3.51156008, 4.4414405 , 2.16309226, 3.45987201,
       1.57329962, 2.44327025, 3.17983988, 0.85553612, 2.27291101,
       3.30741813, 2.61246124, 2.19647792, 3.93898923, 3.43781

>you are at a carnival and come across a person in a booth offering you a game of chance.

>you pay $5 dollars and roll 3 dice. if the sum of the dice rolls is greater than 12 you get 15 dollars. if its less than or equal to 12 you get nothin.


>assuming the dice are fair, should you play this game? How would this change if the winning condition was a sum greater than or equal to 12?

1. caluculat P(win)
1. determibn wether we should play

In [121]:
# 1. data representarion, numbers 1-6 represent which side came up on a die
# 2. matricx of random numbers

rolls = np.random.choice([1,2,3,4,5,6], size=(10_000, 3))

rolls


array([[2, 3, 6],
       [1, 3, 4],
       [2, 3, 2],
       ...,
       [6, 2, 5],
       [5, 2, 4],
       [1, 5, 4]])

In [123]:
# 3. aggregate row-wise to get the results of each simulation
sum_of_rolls = rolls.sum(axis=1)
sum_of_rolls

array([11,  8,  7, ..., 13, 11, 10])

In [126]:
p_win = (sum_of_rolls >= 12).mean()

p_win


0.3801

In [129]:
expected_winnings = p_win * 15
expected_winnings

5.7015